name: TestPlugin
main: io.github.twipsta.testplugin.TestPlugin
version: 0.1

commands:
  hello:
    description: My first command!
  
  ptime:
    description: Played Time!
    
  addplayer:
    description: Add a player!    

  getplayer:
    description: Gets a player!

  getplayers:
    description: Gets all the a player!